DROP PROCEDURE IF EXISTS UpdateBestsellers;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
DECLARE TOTAL_RENT, BK_ID INT;
DECLARE FINISHED INT DEFAULT 0;
DECLARE ALL_RENTALS CURSOR FOR Select BOOK_ID, COUNT(*) AS RENTS from RENTS group by BOOK_ID;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
OPEN ALL_RENTALS;

IF NOT EXISTS( SELECT *
            FROM INFORMATION_SCHEMA.COLUMNS
           WHERE table_name = 'books'
             AND column_name = 'BESTSELLER')  THEN 
  ALTER TABLE BOOKS ADD BESTSELLER boolean DEFAULT FALSE; 
END IF;

WHILE (FINISHED = 0) DO
FETCH ALL_RENTALS INTO BK_ID,TOTAL_RENT;
IF TOTAL_RENT > 2 THEN
UPDATE BOOKS SET BESTSELLER = true
WHERE BOOK_ID = BK_ID;
COMMIT;
ELSE
UPDATE BOOKS SET BESTSELLER = false
WHERE BOOK_ID = BK_ID;
COMMIT;
END IF;
END WHILE;
CLOSE ALL_RENTALS; 

END $$

DELIMITER ;

CALL UpdateBestsellers();
SELECT * from BOOKS;