CREATE TABLE IF NOT EXISTS STATS (
STAT_ID INT(11) AUTO_INCREMENT,
STAT_DATE DATETIME NOT NULL,
STAT VARCHAR(20) NOT NULL,
VALUE INT(11) NOT NULL,
PRIMARY KEY (STAT_ID)
);

CREATE OR REPLACE VIEW BESTSELLERS_COUNT AS
(SELECT COUNT(*) FROM BOOKS GROUP BY BESTSELLER HAVING BESTSELLER = true);

USE kodilla_course;

DROP EVENT IF EXISTS UPDATE_BESTSELLERS;

DELIMITER $$

CREATE EVENT UPDATE_BESTSELLERS
   ON SCHEDULE EVERY 1 minute
   DO
   BEGIN
   CALL UpdateBestsellers();
   INSERT INTO STATS (STAT_DATE, STAT, VALUE)
					VALUE(CURTIME(), "BESTSELLERS", (SELECT * FROM BESTSELLERS_COUNT));
   END;
DELIMITER ;

COMMIT;
