CREATE VIEW BOOKS_AND_READERS AS
SELECT RD.READER_ID, RD.FIRSTNAME, RD.LASTNAME, BK.TITLE
   FROM READERS AS RD, BOOKS AS BK, RENTS AS RT
WHERE RT.BOOK_ID = BK.BOOK_ID
   AND RT.READER_ID = RD.READER_ID
ORDER BY RT.RENT_DATE;